spring:
  profiles:
    active: @profile.active@
  application:
    name: @artifactId@-@profile.active@

opentracing:
  jaeger:
    udp-sender:
      host: localhost
      port: 6831
    log-spans: true #是否发送spans时输出日志，生产环境建议关闭该项，调试时可以开启
    probabilistic-sampler:
      sampling-rate: 0.01 # 概率采集的概率设置，范围为0~1的小数，生产环境一般不全量采集
  spring:
    web:
      skip-pattern: "/<your-url-prefix>/*|/api-docs.*|/autoconfig|/configprops|/dump|/health|/info|/metrics.*|/mappings|/swagger.*|.*\\.png|.*\\.css|.*\\.js|.*\\.html|/favicon.ico|/hystrix.stream" # WEB跟踪的URL过滤名单
      enabled: true # 是否开启web跟踪，即项目自身暴露的web接口
      client:
        enabled: true # 是否开启web clientg跟踪，即resttemplate调用外部接口